name: CI with Snyk

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x, 18.x]  # Required Node.js versions
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Debug - List files in repo
        run: ls -la

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Upgrade npm (only for Node 14+)
        if: matrix.node-version >= 14
        run: npm install -g npm@latest  # Only update npm if compatible

      - name: Install required dependencies
        run: npm install sass --save-dev  # Fixes SASS errors

      - name: Install project dependencies
        run: npm install

      - name: Fix security vulnerabilities (skip for Node 15 & 18)
        if: matrix.node-version < 15
        run: npm audit fix --only=prod || echo "Continuing despite audit issues"

      - name: Build the project
        run: npm run build --if-present

      - name: Run tests
        run: npm test

  publish:
    needs: [security, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Debug - List files before publishing
        run: ls -la

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Use stable Node.js version for publishing
          registry-url: 'https://registry.npmjs.org'

      - name: Upgrade npm
        run: npm install -g npm@latest  # Ensures npm is updated for publishing

      - name: Install dependencies
        run: npm install

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
