name: CI with Snyk

on: 
  push:
  pull_request:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Debug - List files in repo
        run: ls -la

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          if [ -d "lab5" ]; then cd lab5; fi
          npm ci

      - name: Build the project
        run: |
          if [ -d "lab5" ]; then cd lab5; fi
          npm run build --if-present

      - name: Run tests
        run: |
          if [ -d "lab5" ]; then cd lab5; fi
          npm test

  publish:
    needs: [security, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Debug - List files before publishing
        run: ls -la

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '15.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: |
          if [ -d "lab5" ]; then cd lab5; fi
          npm ci

      - name: Publish
        run: |
          if [ -d "lab5" ]; then cd lab5; fi
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
