name: CI with Snyk

on: 
  push:
  pull_request:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Debug: List files in repo
        run: ls -la
       
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci
        working-directory: lab5  # Change if needed

      - name: Build the project
        run: npm run build --if-present
        working-directory: lab5  # Change if needed

      - name: Run tests
        run: npm test
        working-directory: lab5  # Change if needed

  publish:
    needs: [security, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Debug: List files before publishing
        run: ls -la

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '15.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci
        working-directory: lab5  # Change if needed

      - name: Publish
        run: npm publish
        working-directory: lab5  # Change if needed
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}