name: CI with Snyk

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]  # Updated to latest stable LTS version
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Debug - List files in repo
        run: ls -la

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Upgrade npm
        run: npm install -g npm@latest  # Fixes package-lock.json issues

      - name: Install required dependencies
        run: npm install sass --save-dev  # Fixes SASS errors

      - name: Install project dependencies
        run: npm install

      - name: Fix security vulnerabilities
        run: npm audit fix --force

      - name: Build the project
        run: npm run build --if-present

      - name: Run tests
        run: npm test

  publish:
    needs: [security, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Debug - List files before publishing
        run: ls -la

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Upgrade npm
        run: npm install -g npm@latest  # Ensures npm is updated for publishing

      - name: Install dependencies
        run: npm install

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
